In [13]:
import requests

url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1"

autheader = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkYWM3Y2Q0Yjg1NzhkMjBmYWI3ZTUzN2I4YWQwZGQ2ZSIsInN1YiI6IjY0YTViYWNiOGM0NGI5MDBhZTYwOTc5NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jcSzVEVS9LEBjmG2Qa5-dIQ2rgJuYF1NycFK3U7LYs8"
}

response = requests.get(url, headers=autheader)

In [14]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 110.136,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'title': 'The Godfather',
  'video': False,
  'vote_average': 8.7,
  'vote_count': 18170},
 {'adult': False,
  'backdrop_path': '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 85.15,
  'poster_path': '/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg',
  'release_date': '1994-09-23',
  'title': 'The Shawshank Redemption',
  'video': False,
  'vote_average': 8.7,
  'vote_count': 24057},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 61.324,
  'poster_path': '/bMadFzhjy9T7R8J48QGq1ngWNAK.jpg',
  'release_date': '1974-12-20',
  'title': 'The Godfather Part II',
  'video': False,
  'vote_average': 8.6,
  'vote_count': 10966},
 {'adult': False,
  'backdrop_path': '/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 28.548,
  'poster_path': '/ktejodbcdCPXbMMdnpI9BUxW6O8.jpg',
  'release_date': '1995-10-20',
  'title': 'Dilwale Dulhania Le Jayenge',
  'video': False,
  'vote_average': 8.6,
  'vote_count': 4160},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 47.065,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'title': "Schindler's List",
  'video': False,
  'vote_average': 8.6,
  'vote_count': 14220},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 37.372,
  'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
  'release_date': '1957-04-10',
  'title': '12 Angry Men',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 7375},
 {'adult': False,
  'backdrop_path': '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 70.133,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'title': 'Spirited Away',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 14499},
 {'adult': False,
  'backdrop_path': '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
  'genre_ids': [28, 12, 16, 878],
  'id': 569094,
  'original_language': 'en',
  'original_title': 'Spider-Man: Across the Spider-Verse',
  'overview': 'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
  'popularity': 1542.139,
  'poster_path': '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
  'release_date': '2023-05-31',
  'title': 'Spider-Man: Across the Spider-Verse',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 2026},
 {'adult': False,
  'backdrop_path': '/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
  'genre_ids': [10749, 16, 18],
  'id': 372058,
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 84.999,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-08-26',
  'title': 'Your Name.',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 9985},
 {'adult': False,
  'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 61.56,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'title': 'Parasite',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 15943},
 {'adult': False,
  'backdrop_path': '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 63.846,
  'poster_path': '/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg',
  'release_date': '1999-12-10',
  'title': 'The Green Mile',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 15561},
 {'adult': False,
  'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
  'genre_ids': [18, 28, 80, 53],
  'id': 155,
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 77.748,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-14',
  'title': 'The Dark Knight',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 29986},
 {'adult': False,
  'backdrop_path': '/ejnlCzBd5pOGAYCpxC93NXSrdrz.jpg',
  'genre_ids': [35, 14],
  'id': 772071,
  'original_language': 'es',
  'original_title': 'Cuando Sea Joven',
  'overview': '70-year-old Malena gets a second chance at life when she magically turns into her 22-year-old self. Now, posing as "Maria" to hide her true identity, she becomes the lead singer of her grandson\'s band and tries to recover her dream of singing, which she had to give up at some point.',
  'popularity': 18.123,
  'poster_path': '/6gIJuFHh5Lj4dNaPG3TzIMl7L68.jpg',
  'release_date': '2022-09-14',
  'title': 'Cuando Sea Joven',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 243},
 {'adult': False,
  'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  'genre_ids': [53, 80],
  'id': 680,
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 70.294,
  'poster_path': '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
  'release_date': '1994-09-10',
  'title': 'Pulp Fiction',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 25380},
 {'adult': False,
  'backdrop_path': '/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 13,
  'original_language': 'en',
  'original_title': 'Forrest Gump',
  'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
  'popularity': 63.406,
  'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
  'release_date': '1994-06-23',
  'title': 'Forrest Gump',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 24897},
 {'adult': False,
  'backdrop_path': '/eoCSp75lxatmIa6aGqfnzwtbttd.jpg',
  'genre_ids': [37],
  'id': 429,
  'original_language': 'it',
  'original_title': 'Il buono, il brutto, il cattivo',
  'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
  'popularity': 52.886,
  'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
  'release_date': '1966-12-23',
  'title': 'The Good, the Bad and the Ugly',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 7493},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
  'popularity': 62.226,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-01',
  'title': 'The Lord of the Rings: The Return of the King',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 21793},
 {'adult': False,
  'backdrop_path': '/uBZQOYZLIU9dBmd62fdzBAoropu.jpg',
  'genre_ids': [28, 12, 16, 18],
  'id': 704264,
  'original_language': 'en',
  'original_title': 'Primal: Tales of Savagery',
  'overview': "Genndy Tartakovsky's Primal: Tales of Savagery features a caveman and a dinosaur on the brink of extinction. Bonded by tragedy, this unlikely friendship becomes the only hope of survival.",
  'popularity': 13.179,
  'poster_path': '/9NBBkdxH0TjQEBSN2AzeE1sgsF9.jpg',
  'release_date': '2019-11-21',
  'title': 'Primal: Tales of Savagery',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 268},
 {'adult': False,
  'backdrop_path': '/sw7mordbZxgITU877yTpZCud90M.jpg',
  'genre_ids': [18, 80],
  'id': 769,
  'original_language': 'en',
  'original_title': 'GoodFellas',
  'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
  'popularity': 43.936,
  'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
  'release_date': '1990-09-12',
  'title': 'GoodFellas',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 11387},
 {'adult': False,
  'backdrop_path': '/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg',
  'genre_ids': [18, 10749],
  'id': 11216,
  'original_language': 'it',
  'original_title': 'Nuovo Cinema Paradiso',
  'overview': "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
  'popularity': 29.42,
  'poster_path': '/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg',
  'release_date': '1988-11-17',
  'title': 'Cinema Paradiso',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 3800}]

In [16]:
import pandas as pd

In [20]:
pd.DataFrame(response.json()['results']).head(2)

,id,title,overview,release_date,popularity,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,110.136,8.7,18170
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,85.150,8.7,24057

In [23]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

,id,title,overview,release_date,popularity,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,110.136,8.7,18170
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,85.150,8.7,24057
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,61.324,8.6,10966
3,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,28.548,8.6,4160
4,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,47.065,8.6,14220
5,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,37.372,8.5,7375
6,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,70.133,8.5,14499
7,569094,Spider-Man: Across the Spider-Verse,"After reuniting with Gwen Stacy, Brooklyn’s fu...",2023-05-31,1542.139,8.5,2026
8,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,84.999,8.5,9985
9,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,61.560,8.5,15943
10,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,63.846,8.5,15561
11,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-14,77.748,8.5,29986
12,772071,Cuando Sea Joven,70-year-old Malena gets a second chance at lif...,2022-09-14,18.123,8.5,243
13,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,70.294,8.5,25380
14,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,63.406,8.5,24897
15,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,52.886,8.5,7493
16,122,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,2003-12-01,62.226,8.5,21793
17,704264,Primal: Tales of Savagery,Genndy Tartakovsky's Primal: Tales of Savagery...,2019-11-21,13.179,8.5,268
18,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,43.936,8.5,11387
19,11216,Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",1988-11-17,29.420,8.5,3800

In [24]:
pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']].head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,110.136,8.7,18170
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,85.150,8.7,24057
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,61.324,8.6,10966
3,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,28.548,8.6,4160
4,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,47.065,8.6,14220

In [40]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [50]:
# for i in range(1,429):
#     response = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={i}')
#     temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
#     df = df.append(temp_df,ignore_index=True)

# url = 

# autheader = {
#     "accept": "application/json",
#     "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkYWM3Y2Q0Yjg1NzhkMjBmYWI3ZTUzN2I4YWQwZGQ2ZSIsInN1YiI6IjY0YTViYWNiOGM0NGI5MDBhZTYwOTc5NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jcSzVEVS9LEBjmG2Qa5-dIQ2rgJuYF1NycFK3U7LYs8"
# }

# response = requests.get(url, headers=autheader)


for i in range(1,2): #out of 429 only 2 pages has taken
    response = requests.get("https://api.themoviedb.org/3/movie/top_rated?language=en-US&&page={}".format(i), headers=autheader)
    # response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

    # df = df.append(temp_df)
    df = pd.concat([df,temp_df])

In [51]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,110.136,8.7,18170
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,85.150,8.7,24057
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,61.324,8.6,10966
3,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,28.548,8.6,4160
4,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,47.065,8.6,14220
5,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,37.372,8.5,7375
6,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,70.133,8.5,14499
7,569094,Spider-Man: Across the Spider-Verse,"After reuniting with Gwen Stacy, Brooklyn’s fu...",2023-05-31,1542.139,8.5,2026
8,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,84.999,8.5,9985
9,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,61.560,8.5,15943
10,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,63.846,8.5,15561
11,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-14,77.748,8.5,29986
12,772071,Cuando Sea Joven,70-year-old Malena gets a second chance at lif...,2022-09-14,18.123,8.5,243
13,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,70.294,8.5,25380
14,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,63.406,8.5,24897
15,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,52.886,8.5,7493
16,122,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,2003-12-01,62.226,8.5,21793
17,704264,Primal: Tales of Savagery,Genndy Tartakovsky's Primal: Tales of Savagery...,2019-11-21,13.179,8.5,268
18,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,43.936,8.5,11387
19,11216,Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",1988-11-17,29.420,8.5,3800

In [52]:
df.shape

(20, 7)

In [ ]:
df.to_csv('movies.csv')

In [39]:
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,119738,Thunderstruck,After NBA star Kevin Durant switches talent wi...,2012-08-24,13.758,6,208
1,11915,The Gendarme and the Gendarmettes,Cruchot's police office moves into a new build...,1982-10-03,13.624,6,482
2,520663,The Woman in the Window,An agoraphobic woman living alone in New York ...,2021-05-13,12.654,6,1724
3,335866,Circle,"In a massive, mysterious chamber, fifty strang...",2015-05-28,13.917,6,1756
4,77883,The Possession,A young girl buys an antique box at a yard sal...,2012-08-30,17.674,6,1456
5,9268,Eraser,U.S. Marshall John Kruger erases the identitie...,1996-06-21,21.186,6,1604
6,611914,The Courier,"Ezekiel Mannings, a vicious crime boss, is out...",2019-11-22,23.470,6,488
7,24913,April Fool's Day,A group of eight college friends gather togeth...,1986-03-27,9.818,6,280
8,8130,Desperately Seeking Susan,Roberta is a bored suburban housewife who is f...,1985-03-29,10.634,6,374
9,3563,I Now Pronounce You Chuck & Larry,Firefighters Chuck Ford and Larry Valentine ar...,2007-07-12,21.034,6,2077
10,351964,The Escort,"Desperate for a good story, a sex-addicted jou...",2015-11-05,18.447,6,370
11,347984,6 Days,"London, England, April 1980. Six terrorists as...",2017-07-09,14.811,6,631
12,76494,What to Expect When You're Expecting,Challenges of impending parenthood turn the li...,2012-05-17,16.167,6,1675
13,46503,All Good Things,"Newly-discovered facts, court records and spec...",2010-12-03,11.709,6,798
14,718400,The Vanished,A family vacation takes a terrifying turn when...,2020-08-21,14.239,6,256
15,289727,The Rewrite,An Oscar-winning writer in a slump leaves Holl...,2014-06-15,10.628,6,531
16,13252,Cleaner,Single father and former cop Tom Cutler has an...,2007-09-11,11.698,6,726
17,11675,Halloween H20: 20 Years Later,Two decades after surviving a massacre on Octo...,1998-08-05,19.655,6,1439
18,10724,Firefox,The Soviets have developed a revolutionary new...,1982-06-13,15.298,6,463
19,9416,Money Talks,"Sought by police and criminals, a small-time h...",1997-08-22,9.760,6,317